### PR TITLE
I31 roslint

### PR DESCRIPTION
**Pull request by stevenwaslander**
This pull request addresses issue #33, not sure why I thought it was 31.

A few concerns before merging to master.
1. I can only confirm that the changes did not affect the main mcptam code's ability to run on the FlightArena.bag.  I have not checked the quality of the solution, or any of the other executables, such as server/client or calibration.
2. It is unclear how this edit of syntax will affect the other code changes in progress.
3.  This will be somewhat hard to review, but 99% of the changes are one of the following:
   a) space removal at end of line
   b) .cc changed to .cpp
   b) include what you use
   c) remove using namespace directives in favour of namespace:: declarations, mostly in the code, but a few heavily repeated ones added at the top of the cpp files.
   d) c++ style static_cast instead of c-style typecast.
   e) rand_r with a seed instead of the unthreadsafe rand.
4. It would be good to add an automated roslint check to the CI. Likely a new issue.

### CODE REVIEW

**Comment by stevenwaslander** [comment]
OK, managed to run client/server mode on one laptop, although the images were smaller, the buttons on the interface were not visible.  Have added an issue to fix gui in server mode, not sure why it's different.

**Comment by stevenwaslander** [comment]
Added the roslint CI issue too.  If one person is willing to look through the pull request, I think we're good to go.

**Comment by arunxdas** [comment]
Maybe Stan and I can spend an afternoon next week and look this over?

**Comment by stevenwaslander** [comment]
Sounds good, the merge with cper fails, but I can sort through it once we've finished this pull request.

**Comment by arunxdas** [comment]
ok, I pulled this branch and can confirm it runs with the rockface, flight arena bag, and a newer bag I collected for IROS.  I also added the CI test for roslint.  I don't think it's necessary to go through all 3000 line changes, seeing how most changes are one of the above, as @stevenwaslander mentioned.  Can we merge with master branch, or are there any other tests we can run though?

**Comment by arunxdas** [comment]
also, seems to fail roslint on Travis CI.  Any thoughts on why this is happening?  It passes on my machine just fine

**Comment by stevenwaslander** [comment]
Maybe let's separate the travis CIing of roslint from this issue, so we can finish it and move on to the big merge.  I don't see anything useful in the Travis log files on why the roslint test is failing

**Comment by stevenwaslander** [comment]
never mind, looks like Stan fixed it.  And now to fix the merge issue. I'm on it.

**Comment by stevenwaslander** [comment]
Closes #33 and #37

**Pull request merged**
